"""
Created on Dec 8, 2025

@author: CyberiaResurrection
"""
import logging

from typing import Any, Optional
from typing_extensions import TypeAlias

from PyRoute.AreaItems.Galaxy import Galaxy
from PyRoute.Outputs.Cursor import Cursor
from PyRoute.Outputs.Colour import Colour

Scheme: TypeAlias = str


class MapOutput(object):
    def __init__(self, galaxy: Galaxy, routes: str, output_path: str, writer: str):
        self.output_path: str = output_path
        self.doc: Optional[Any] = None
        self.logger = logging.getLogger('PyRoute.Outputs.MapOutput')

        self.image_size: Cursor = Cursor(0, 0)

        self.fonts: dict[Scheme, Any] = {
            'title': None,
            'info': None,
            'sector': None,
            'system_port': None,
            'system_uwp': None,
            'system_name': None,
            'base code': None
        }
        self.colours: dict[Scheme, Colour] = {
            'background': None,
            'title': None,
            'info': None,
            'sector': None,
            'system_port': None,
            'system_uwp': None,
            'system_name': None,
            'base code': None,

            'grid': None,
            'hexes': None,
            'red zone': None,
            'amber zone': None,
            'gg refuel': None,
            'wild refuel': None,
            'comm': None,
        }

    def document(self, sector: str, is_live: bool = True) -> Any:
        """
        Generated by the type of document
        """
        raise NotImplementedError("Base Class")

    def close(self) -> None:
        raise NotImplementedError("Base Class")

    def add_line(self, start: Cursor, end: Cursor, colour: Colour, stroke: str = 'solid', width: float = 1) -> None:
        """
        Add a line to the document, from start to end, in colour
        """
        raise NotImplementedError("Base Class")

    def add_rectangle(self, start: Cursor, end: Cursor, border_colour: Colour, fill_colour: Colour, width: int) -> None:
        """
        Add a filled rectangle to the document, upper right -> lower left, border + fill colour.
        :param start:
        :param end:
        :param border_colour:
        :param fill_colour:
        :param width:
        :return:
        """
        raise NotImplementedError("Base Class")

    def add_text(self, text: str, start: Cursor, scheme: Scheme) -> None:
        raise NotImplementedError("Base Class")

    def add_text_centred(self, text: str, start: Cursor, scheme: Scheme, max_width: int = -1, offset: bool = False) -> None:
        raise NotImplementedError("Base Class")

    def add_text_centred_legacy(self, text: str, start: Cursor, scheme: Scheme, max_width: float = -1.0) -> None:
        raise NotImplementedError("Base Class")

    def add_text_rotated(self, text: str, start: Cursor, scheme: Scheme, rotation: int) -> None:
        raise NotImplementedError("Base Class")

    def add_text_right_aligned(self, text: str, start: Cursor, scheme: Scheme) -> None:
        raise NotImplementedError("Base Class")

    def add_circle(self, center: Cursor, radius: int, line_width: int, fill: bool, scheme: Scheme) -> None:
        """
        Add a circle to the document, from start to end, in colour
        """
        raise NotImplementedError("Base Class")

    def get_font(self, scheme: Scheme) -> Any:
        return self.fonts[scheme]

    def get_colour(self, scheme: Scheme) -> Any:
        return self._get_colour(self.colours[scheme])

    @staticmethod
    def _get_colour(colour: Colour):
        raise NotImplementedError("Base Class")

    @staticmethod
    def _get_text_size(font, string: str) -> tuple[int, int]:
        raise NotImplementedError("Base Class")
